const char *vertexKernelSource = 
"void matrixByVector(float* matrix, float* vector){"
    "float x = vector[0];"
    "float y = vector[1];"
    "float z = vector[2];"
    "float w = vector[3];"
    "vector[0] = matrix[0] * x + matrix[1] * y + matrix[2] * z + matrix[3] * w;"
    "vector[1] = matrix[4] * x + matrix[5] * y + matrix[6] * z + matrix[7] * w;"
    "vector[2] = matrix[8] * x + matrix[9] * y + matrix[10] * z + matrix[11] * w;"
    "vector[3] = matrix[12] * x + matrix[13] * y + matrix[14] * z + matrix[15] * w;"
"}"
"__kernel void vector_matrix_multiply(__global const float* vertices, "
                                     "__global const float* matrices,"
                                     "__global float* outputVertices,"
                                     "const int matrixCount,"
                                     "const int height,"
                                     "const int width) { "
    "int vertex = get_global_id(0);"
    "float temp[4];"
    "for(int i = 0; i < 3; i++){ temp[vertex + i] = vertices[vertex + i]; }"
    "temp[3] = 1.0;"
    "for(int i = 0; i < matrixCount * 16; i += 16){"
    "   matrixByVector(&matrices[i], temp);"
    "}"
    "//perspective division"
    "if(temp[3] >= 1.0){"
    "   temp[i] = temp[i] / temp[3];"
    "   temp[i + 1] = temp[i + 1] / temp[3];"
    "}"
    "//screen space conversion"
    "temp[i] *= width;"
    "temp[i + 1] *= height;"
    "temp[i + 3] *= height;"
    "for(int i = 0; i < 3; i++) { outputVertices[vertex + i] = temp[i]; }"
"}";